// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import CommentFormController from "./comment_form_controller"
application.register("comment-form", CommentFormController)

import FollowButtonController from "./follow_button_controller"
application.register("follow-button", FollowButtonController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PostFormController from "./post_form_controller"
application.register("post-form", PostFormController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import UploadAvatarController from "./upload_avatar_controller"
application.register("upload-avatar", UploadAvatarController)
